### ISSUE TITLE
scikit-learn should not be a dependency or should it ?

### ISSUE THREAD

**Issue by fretchen** [Qiskit-Extensions/qiskit-cold-atom#18]
Right now installs are complicated for me as `scikit-learn` seems to be a requirement. However, it remains obscure why for me.

**Comment by LaurinFischer** [comment]
As of the current requirements (last changed here 79b94f2) `scikit-learn` is not included. Maybe you meant `scipy` which we rely on for their efficient implementations of sparse matrices used by the simulators.
