### ISSUE TITLE
Slight bugs in running first tutorial

### ISSUE THREAD

**Issue by fretchen** [Qiskit-Extensions/qiskit-cold-atom#2]
- The `jupyterlab` has to be installed. Right now the user is not told to do so anywhere it would seem.
- The `pylatexenc` is not automatically installed and the user directly runs into this error as they attempt to run the tutorial 01_introduction. 
- The `ipywidgets` is not automatically installed.

Both seem fixable through the setup.py file and through documentation no ?

**Comment by fretchen** [comment]
Another question that came up:

Is the first input really appropiate ?

```


from qiskit import QuantumCircuit

qc = QuantumCircuit(4)  # Create a quantum circuit describing four fermionic modes.

qc.load_fermions([1, 2])  # Load fermions into modes 1 and 2.

qc.draw(output='mpl')
```

It somehow seems to set up another kind of circuits than afterwards as all the wires are labelled as `fer_mod` instead of `q` afterwards.

**Comment by LaurinFischer** [comment]
To your first point, these can all be installed through the `requirements-dev` via 
```
pip install -r requirements-dev.txt
```
at the project root. Maybe it would make sense to just add it to the normal requirements which the `setup.py` installs under the hood..

**Comment by fretchen** [comment]
Both are fine (the second option bloats the installation slightly more, but allows to come with batteries included).
If the requirement-dev.txt is used, it should be mentionned somewhere in the readme or something like that right ?

**Comment by LaurinFischer** [comment]
Good point, I added a sentence in the Readme. The reason I don't want this in the standard installation is that people have different preferences how to execute `.ipynb` files.
