### ISSUE TITLE
Consistent naming for the fermions

### ISSUE THREAD

**Issue by fretchen** [Qiskit-Extensions/qiskit-cold-atom#40]
### What is the current behavior?
The fermion names are of all kind of different conventions.

### What is the expected behavior?

They should be unified.

### Suggested solutions
The Hamiltonian,  circuit instruction and gate name should have the following names:

FermiHubbard, circ.fhubbard, fhubbard
`Hop`, `circ.fhop`, `fhop`
`Interaction`, `circ.fint`, `fint`
`Phase`, `circ.fphase`, `fphase`
`FRXGate`, `frx`, `frx`

**Comment by eggerdj** [comment]
Closed by #43
